apiVersion: v1
kind: Service
metadata:
  name: {{ include "activemq-artemis.fullname" . }}
  labels:
    {{- include "activemq-artemis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.jolokia.port }}
      targetPort: jolokia
      protocol: TCP
      name: jolokia
    - port: {{ .Values.service.jmx.port }}
      targetPort: jmx
      protocol: TCP
      name: jmx
  selector:
    {{- include "activemq-artemis.selectorLabels" . | nindent 4 }}
