---
- name: Configure named.conf.local
  template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local

- name: Configure local.lan DNS zone file
  template:
    src: db.local.lan.j2
    dest: /var/lib/bind/db.local.lan

- name: Configure reverse DNS zone file for 192.168.8.x
  template:
    src: db.192.168.8.j2
    dest: /var/lib/bind/db.192.168.8

- name: Configure reverse DNS zone file for 192.168.11.x
  template:
    src: db.192.168.11.j2
    dest: /var/lib/bind/db.192.168.11

- name: Set ownership and permissions for dynamic zone files
  file:
    path: "{{ item }}"
    owner: bind
    group: bind
    mode: '0664'
  with_items:
    - /var/lib/bind/db.local.lan
    - /var/lib/bind/db.192.168.8
    - /var/lib/bind/db.192.168.11

- name: Configure the DNS tsig key to allow DHCP to update DNS
  template:
    src: dhcp-ddns-key.conf.j2
    dest: /etc/bind/dhcp-ddns-key.conf

- name: Set ownership and permissions for key files
  file:
    path: "{{ item }}"
    owner: bind
    group: bind
    mode: '0600'
  with_items:
    - /etc/bind/rndc.key
    - /etc/bind/dhcp-ddns-key.conf

- name: Ensure forwarders are configured in named.conf.options
  blockinfile:
    path: /etc/bind/named.conf.options
    marker: "        # {mark} ANSIBLE MANAGED FORWARDERS"
    block: |
        forwarders {
            8.8.8.8; // Google DNS
            1.1.1.1; // Cloudflare DNS
        };
    insertafter: '^options {'

- name: Restart BIND service to apply changes
  service:
    name: bind9
    state: restarted

