apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: pi-cluster-charts
  namespace: flux-system
spec:
  interval: 1m
  url: ssh://git@github.com/thatmikewilliams/pi-cluster
  ref:
    branch: main
  secretRef:
    name: charts-key
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/deployment/charts
