- name: install docker dependencies
  become: yes
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - lsb-release
      - gnupg
    state: latest
    update_cache: true

- name: add docker signing key
  become: yes
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present

- name: add docker repository into sources list
  become: yes
  apt_repository:
    repo: "deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
    filename: docker

- name: install docker
  become: yes
  apt:
    name:
      - docker
      - docker.io
      - docker-compose
      - docker-registry
    state: latest
    update_cache: true

- name: ensure docker service is started
  service:
    name: docker
    state: started
    enabled: yes

- name: adding existing user '{{ ansible_user }}' to docker group
  become: yes
  user:
    name: '{{ ansible_user }}'
    groups: docker
    append: yes
