- name: Update apt package index
  apt:
    update_cache: yes

- name: Ensure dependencies are installed
  apt:
    name:
      - ca-certificates
      - curl
    state: present

- name: Create directory for Docker GPG key
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker's GPG key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Map architecture for Docker (there is no aarch64 docker package - needs to be arm64)
  set_fact:
    docker_architecture: "{{ 'arm64' if ansible_architecture == 'aarch64' else ansible_architecture }}"

- name: Add Docker Apt repository
  apt_repository:
    repo: "deb [arch={{ docker_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: docker

- name: Update apt package index again
  apt:
    update_cache: yes

- name: Install Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Ensure Docker service is started
  service:
    name: docker
    state: started
    enabled: yes

- name: Adding existing user '{{ ansible_user }}' to docker group
  become: yes
  user:
    name: '{{ ansible_user }}'
    groups: docker
    append: yes

