---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  releaseName: cert-manager
  interval: 120m
  chart:
    spec:
      chart: deployment/charts/cert-manager
      version: '*'
      sourceRef:
        kind: GitRepository
        name: charts
        namespace: flux-system
      # Don't need to pull charts for cert-manager every 5mins incressing this to every 12 hours.
      # Will have to change the value to <= 5mins when upgrading
      interval: 12h
  install:
    remediation:
      retries: 5
  upgrade:
    disableWait: true
    remediation:
      retries: 1
      strategy: rollback
    timeout: 30s
  values:
    # Default values for cert-manager.
    # This is a YAML-formatted file.
    # Declare variables to be passed into your templates.
    global:
      rbac:
        aggregateClusterRoles: false
    installCRDs: true
    prometheus:
      enabled: false
