---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: activemq-artemis
  namespace: test
spec:
  chart:
    spec:
      chart: deployment/charts/activemq-artemis
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: pi-cluster-charts
  interval: 1m0s
  values:
    affinity: {}
    autoscaling:
      enabled: false
      maxReplicas: 100
      minReplicas: 1
      targetCPUUtilizationPercentage: 80
    fullnameOverride: ""
    image:
      pullPolicy: IfNotPresent
      repository: ghcr.io/thatmikewilliams/apache/activemq-artemis
      tag: 2.30.0-ubuntu-11
    imagePullSecrets:
      - name: regcred
    ingress:
      annotations: {}
      className: ""
      enabled: false
      hosts:
      - host: chart-example.local
        paths:
        - path: /
          pathType: ImplementationSpecific
      tls: []
    nameOverride: ""
    nodeSelector: {}
    podAnnotations: {}
    podSecurityContext: {}
    replicaCount: 1
    resources: {}
    securityContext: {}
    service:
      port: 80
      type: ClusterIP
    serviceAccount:
      annotations: {}
      create: true
      name: ""
    tolerations: []

