---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: activemq-artemis
  namespace: test
spec:
  chart:
    spec:
      chart: deployment/charts/activemq-artemis
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: pi-cluster-charts
  interval: 1m0s
  values:
    affinity: {}
    autoscaling:
      enabled: false
      maxReplicas: 100
      minReplicas: 1
      targetCPUUtilizationPercentage: 80
    fullnameOverride: ""
    image:
      pullPolicy: IfNotPresent
      repository: ghcr.io/thatmikewilliams/apache/activemq-artemis
      tag: 2.30.0-ubuntu
    imagePullSecrets:
      - name: regcred

    ingress:
      annotations: {}
      className: ""
      enabled: false
      hosts:
      - host: chart-example.local
        paths:
        - path: /
          pathType: ImplementationSpecific
      tls: []
    nameOverride: ""
    nodeSelector: {}
    podAnnotations: {}
    podSecurityContext: {}
    replicaCount: 1

    resources:
      limits:
        memory: 1000Mi
      requests:
        memory: 1000Mi

    securityContext: {}
    serviceAccount:
      annotations: {}
      create: true
      name: ""
    tolerations: []

    env:
      jvmArgs: "-XX:InitialRAMPercentage=85 -XX:MinRAMPercentage=85 -XX:MaxRAMPercentage=85 -Dcom.sun.management.jmxremote.port=1234i -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.ssl=false -XX:+PrintClassHistogram -XX:+UseG1GC -XX:+UseStringDeduplication -Dhawtio.realm=activemq -Dhawtio.offline=true -Dhawtio.rolePrincipalClasses=org.apache.activemq.artemis.spi.core.security.jaas.RolePrincipal -Djolokia.policyLocation=file:/var/lib/artemis-instance/etc/jolokia-access.xml"

