apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: test
spec:
  encryptedData:
    .dockerconfigjson: AgCB6BopyEsLyhhU5pHU0YJGRHxUlkVVAiGsfBbKlA0XHB2OU2YCfCXg4OuGs6FQJq/cm/XBiYto5l8BJSxlFkji0Is/gX/y3jG1bepUMNB5zGjXRz9NzOZGYVXLfo5ps+v+fYzTeDc2NDy7ntSHA7hrau5ZzD9ozH7xbc4q8a7TUuwPMOCZR+DxZKaSd0r0p6XwhvHQ+V6mNthHxAmVP26yFLW3RvPH8+N0xHE97WMm6j6nEbzhRgfWKRFg7Fjq/Oe6o8xqz2w4C+rxftVd2oFDvuilcPs2WnXKCQ7vcXCNfHpMVoeKDRLKfHLn+vogKJZ0bB2iJX+GmsxXmCC5QlMdOMaitIVU5c4ywHtc0h4uj5oCzlnaAfzuhjk2gEw4zaaLKAW2Ak7TEeOkyQhYXd5AAq/8+A4MSzg/t9+h4U5+64gD15upaZ23fqqo00oECmYvC0thip5wXFltmXZjDpf72dupbgbZVQBKPqlE6Mgzx3TDimP2u8du0y9hdsqvWOzXoQb6rGD7ZBS5MrWtlKIpW5c3jIyCv1mGfXkfr4vmx0kYSmOa5BdESXu2RpxuhjQvV0kaisZlID30rD3W/TI4nZYqxeM9N5OV6pWvDgrTK4Q1Zcn0Bzq2nGdd02kreFXhcs/wB+5BxWwKHEXWh12OAQoGTMMB+JrX2hjW3rQRfqitczNqMbQmQ/crIShVGo4TEcVDopGsyvzuLL1fChr/fwMe4K92dQ9SeAmZK+CjRB2cAq2zp8gGULvq5Q/ZCVg//s0EFAUNRDm/Dwg904y1wOybrSVuQ0wpC2icqlsYtVNke51gmxhUH2+5Mrj82+sbc3QV2xenUjWRAnrG
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: test
    type: kubernetes.io/dockerconfigjson

