---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: neo4j-test
  namespace: test
spec:
  chart:
    spec:
      chart: deployment/charts/neo4j-standalone
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: pi-cluster-charts
  interval: 1m0s

  values:
    neo4j:
      name: neo4j1
      resources:
        requests:
         cpu: "1000m"
         memory: "2Gi"
        limits:
         cpu: "2000m"
         memory: "4Gi"
      volumes:
        data:
          mode: defaultStorageClass
          defaultStorageClass:
            accessModes:
              - ReadWriteOnce
            requests:
              storage: 2Gi

