---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: neo4j-test
  namespace: test1
spec:
  chart:
    spec:
      chart: deployment/charts/neo4j-standalone
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: pi-cluster-charts
  interval: 1m0s

