- name: Print all available facts
  ansible.builtin.debug:
    var: ansible_facts

- name: be sure ntp is installed
  apt:
    name: ntp
    state: present
  become: yes
  tags: ntp

    #- name: be sure ntp is configured
    #  template:
    #    src: ntp.conf.j2
    #    dest: /etc/ntp.conf
    #  notify:
    #    - restart ntpd
    #  tags: ntp

- name: be sure ntp is running and enabled
  service:
    name: ntp
    state: started
    enabled: yes
  become: yes
  tags: ntp


- name: Upgrade the OS (apt-get update && apt-get upgrade)
  ansible.builtin.apt:
    update_cache: yes
    upgrade: full
  become: yes

- name: Clean unwanted old packages and config
  ansible.builtin.apt:
    autoremove: yes
    purge: yes
  become: yes
