name: sealed-secrets
description: Helm chart for the sealed-secrets controller.

##############################
# Important versioning rules #
##############################
#
# Please keep the chart version in sync with the app version
# and use -rN suffixes (e.g. -r2)
#
# Since the helm chart started with 1 and we don't want discontinuities,
# for a while the helm chart version will be 1.x.y and the appVersion 0.x.y
#

version: 1.15.0-r3
appVersion: v0.15.0

icon: https://avatars0.githubusercontent.com/u/34656521?s=200&v=4
kubeVersion: ">=1.16.0-0"
home: https://github.com/bitnami-labs/sealed-secrets
apiVersion: v2
type: application
maintainers:
- name: mkmik
  email: mmikulicic@gmail.com
