---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-crds
  namespace: linkerd
spec:
  releaseName: linkerd-crds
  interval: 5m
  chart:
    spec:
      chart: deployment/charts/linkerd-edge/linkerd-crds
      version: '*'
      sourceRef:
        kind: GitRepository
        name: charts
        namespace: flux-system
      interval: 1m
  install:
    disableWait: true
    remediation:
      retries: 5
  upgrade:
    disableWait: true
    remediation:
      retries: 1
      strategy: rollback
    timeout: 60s
  values:
    cniEnabled: true
