---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-control-plane
  namespace: linkerd
spec:
  releaseName: linkerd-control-plane
  interval: 5m
  chart:
    spec:
      chart: deployment/charts/linkerd-edge/linkerd-control-plane
      version: '*'
      sourceRef:
        kind: GitRepository
        name: charts
        namespace: flux-system
      interval: 1m
  install:
    disableWait: true
    remediation:
      retries: 5
  upgrade:
    disableWait: true
    remediation:
      retries: 1
      strategy: rollback
    timeout: 60s
  values:
    cniEnabled: true
    networkValidator:
      # -- Timeout before network-validator fails to validate the pod's network connectivity
      timeout: "30s"

    identityTrustAnchorsPEM: |
      -----BEGIN CERTIFICATE-----
      MIIBjDCCATOgAwIBAgIQbr7OG6sBzw9kOfXgMPOwVDAKBggqhkjOPQQDAjAlMSMw
      IQYDVQQDExpyb290LmxpbmtlcmQuY2x1c3Rlci5sb2NhbDAeFw0yNDEwMDMxNjU2
      MDRaFw0zNDEwMDExNjU2MDRaMCUxIzAhBgNVBAMTGnJvb3QubGlua2VyZC5jbHVz
      dGVyLmxvY2FsMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEPDUw0riuqgyjj5t6
      BtGovni/0CVraB8JJooYbN9+u3V8o0iP7o/JXBqG+bVrTLgJHcVU3rkrqKWfQCcp
      BTycXqNFMEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwHQYD
      VR0OBBYEFEWwcMqoOdbVNUzGcsI+gcXm0L9PMAoGCCqGSM49BAMCA0cAMEQCID39
      2oBGQ9Zg1XxuTvcFsNgGytpvMKArAWe0bET9K/h+AiAlWutE/yW6UdL461nuLIMH
      sGfS4bIqfS8yDUXiEMcwhQ==
      -----END CERTIFICATE-----

    proxy:
      # -- Default set of opaque ports
      # - SMTP (25,587) server-first
      # - JMX (1099)
      # - MYSQL (3306) server-first
      # - Hermes (4317,4318)
      # - Galera (4444) server-first
      # - PostgreSQL (5432) server-first
      # - Neo4j backup (6362)
      # - Redis (6379) server-first
      # - Neo4j (7474,7687)
      # - ElasticSearch (9300) server-first
      # - Memcached (11211) clients do not issue any preamble, which breaks detection
      # - Corda Node (14000,14001,14002,14003)
      # - ActiveMQ broker port (61616)
      opaquePorts: "25,587,1099,3306,4317,4318,4444,5432,6363,6379,7474,7687,9300,11211,14000,14001,14002,14003,61616"

      # Enables the proxy's /shutdown admin endpoint
      # We need this to allow cronjobs to tell the proxy to shutdown after 
      # the job has completed, otherwise the proxy container prevents the job 
      # pod from terminating.
      enableShutdownEndpoint: true
      # Delay shutdown of the proxy to allow corda-aceson to execute it's pre-stop-handler.
      # Without the delay, the handler can't install the packages it needs.
      waitBeforeExitSeconds: 20
      # Set the container resource limits for the proxy (to contribute to the pod's overall limit)
      # If a container in a pod doesn't have a limit, the metricbeat stat kubernetes.pod.memory.working_set.limit.pct is not sent.
      # This stat is used to drive the pod memory charts in elastic.
      resources:
        memory:
          request: 20Mi
          limit: 50Mi

    identity:
      issuer:
        scheme: kubernetes.io/tls
