---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-cni
  namespace: linkerd-cni
spec:
  releaseName: linkerd-cni
  interval: 5m
  chart:
    spec:
      chart: deployment/charts/linkerd-edge/linkerd2-cni
      version: '*'
      sourceRef:
        kind: GitRepository
        name: charts
        namespace: flux-system
      interval: 1m
  install:
    disableWait: true
    remediation:
      retries: 5
  upgrade:
    disableWait: true
    remediation:
      retries: 1
      strategy: rollback
    timeout: 60s
  values:
    # -- Run the install-cni container in privileged mode
    privileged: true
